print(" /|             /| ")
print("/  |           /  |")
print("|  |-----------|  |")
print("|  |  ()   ()  |  |")
print("| | |         | | |")
print("||   |  ___  |   ||")
print("|    |  \_/  |    |")
print("      |     |      ")
print("     |       |     ")
print("Типо собака")