print("Привіт. Це гра Mad Libs. Напишіть будь яку назву за критеріями, які будуть виводитися нижче.")
print()
print("-----")
print()
imennik = input("Введіть назву іменнику: ")
kolir = input("Введіть назву кольору: ")
dieslovo = input("Введіть назву дієслова: ")
nazwa_miscia = input("Введіть назву місця: ")
nazwa_twariny = input("Введіть назву тварини: ")
print()
print("-----")
print()
print("Ось результат :3")
print("Одного разу", imennik, "був дуже сумний, тому що він був", kolir+". Він вирішив", dieslovo, "у", nazwa_miscia, "де зустрів", nazwa_twariny + ". Разом вони вирішили залишитися в", nazwa_miscia, "назавжди, і стали найкращими друзями.")
